name: lib_x
description: lib_x is a simple library which includes some well tested, lightweight, and commonly needed packages.
 And on top of those packages, there're some preconfigured solutions and simplifications to help you quickly focus on the scaffold within few steps.
version: 0.0.3
homepage: https://github.com/HazemMonir/lib_x

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  overlay_support: ^2.1.0
  routemaster: ^1.0.1
  back_button_interceptor: ^6.0.2
  http: ^0.13.5
  mime: ^1.0.2
  intl: ^0.17.0
  url_strategy: ^0.2.0
  shimmer: ^2.0.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  # assets:
    # - assets/